PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Oi, {PLAYER}!\p"
    .string "Meu irmão, {RIVAL},\n"
    .string "está no LAB do vovô.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, ouvi\n"
    .string "que você batalhou\l"
    .string "contra o {RIVAL}.\p"
    .string "Queria ter visto!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "O vovô pediu para\n"
    .string "você fazer uma\l"
    .string "tarefa?\p"
    .string "Nossa, que preguiça.\n"
    .string "Aqui, isso vai\l"
    .string "ajudar.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} recebeu o\n"
    .string "MAPA da DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Você não tem espaço\n"
    .string "na sua MOCHILA.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Você pode usar o\n"
    .string "MAPA para saber onde\l"
    .string "está ou ver os nomes\l"
    .string "dos lugares.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Assim como\n"
    .string "pessoas, POKéMON são\l"
    .string "seres vivos.\p"
    .string "Quando cansarem,\n"
    .string "deixe eles\l"
    .string "descansarem.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "É um mapa grande da\n"
    .string "região de KANTO.\l"
    .string "Isso seria útil!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "As prateleiras estão\n"
    .string "cheias de livros\l"
    .string "sobre POKéMON.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Oi, {PLAYER}!\n"
    .string "Boa hora.\p"
    .string "Vou tomar chá.\n"
    .string "Quer tomar comigo?\p"
    .string "Ah, olhe.\n"
    .string "Seus POKéMON estão\l"
    .string "um pouco sujos.\p"
    .string "Quer que eu cuide de\n"
    .string "um deles?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "Não precisa cuidar?\n"
    .string "Certo, vamos só\l"
    .string "tomar chá.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "De qual devo cuidar?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Certo, vou\n"
    .string "deixá-lo bonito\l"
    .string "rapidinho.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} parece\n"
    .string "feliz e sonhador…\p"
    .string "{COLOR RED}DAISY: Pronto!\n"
    .string "Terminei.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} parece\n"
    .string "feliz e sonhador…\p"
    .string "{FONT_FEMALE}DAISY: Pronto!\n"
    .string "Terminei.\n"
#endif
    .string "Viu? Não ficou lindo?\p"
    .string "Hehe…\n"
    .string "É um POKéMON tão\l"
    .string "fofo.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Ah, desculpe. Eu não\n"
    .string "posso cuidar de um\l"
    .string "OVO.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Seus POKéMON\n"
    .string "te amam se você\l"
    .string "cuida deles com amor.\p"
    .string "Por exemplo,\n"
    .string "{PLAYER}, posso ver\l"
    .string "seu primeiro POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "Ele não poderia te\n"
    .string "amar mais do que ama\l"
    .string "agora.\p"
    .string "Seu POKéMON está\n"
    .string "feliz demais para\l"
    .string "descrever.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Ele parece muito\n"
    .string "feliz.\p"
    .string "Queria que {RIVAL}\n"
    .string "visse isso e\l"
    .string "aprendesse algo.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Ele é bem amigável\n"
    .string "com você. Continue\l"
    .string "cuidando bem dele!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Ele está se apegando\n"
    .string "a você. A confiança\l"
    .string "está crescendo.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "Ele ainda não está\n"
    .string "familiarizado com\l"
    .string "você.\p"
    .string "POKéMON são sempre\n"
    .string "cautelosos quando\l"
    .string "você os pega.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, não gosto\n"
    .string "do jeito que ele\l"
    .string "olha para você.\p"
    .string "Você pode tentar ser\n"
    .string "mais gentil com ele?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Hum, não é fácil\n"
    .string "dizer isso, mas…\p"
    .string "Tem algum motivo\n"
    .string "para seu POKéMON te\l"
    .string "odiar tanto?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string “”O adorável e doce\n”
    .string “CLEFAIRY”$”

