PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Ué, é só o\n"
    .string "{PLAYER}?\l"
    .string "O vovô não está aqui.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Vovô!\n"
    .string "Cansei de esperar!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Ei! Vovô!\n"
    .string "Não é justo!\l"
    .string "E eu?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Heh, eu não\n"
    .string "preciso ser ganancioso\l"
    .string "como você. Sou maduro!\p"
    .string "Vá em frente e\n"
    .string "escolha, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Vou levar\n"
    .string "este então!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} recebeu o\n"
    .string "{STR_VAR_1} do PROF.\l"
    .string "CARVALHO!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Meu POKéMON\n"
    .string "parece bem mais forte\l"
    .string "que o seu.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Espera,\n"
    .string "{PLAYER}!\l"
    .string "Vamos ver nossos\l"
    .string "POKéMON!\p"
    .string "Vamos, vou te\n"
    .string "desafiar!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "O QUÊ?\n"
    .string "Inacreditável!\l"
    .string "Escolhi o POKéMON\l"
    .string "errado!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Isso!\n"
    .string "Sou incrível ou não?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Certo! Vou\n"
    .string "fazer meu POKéMON\l"
    .string "batalhar para ficar\l"
    .string "mais forte!\p"
    .string "{PLAYER}! Vovô!\n"
    .string "Até mais!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Vovô!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Quase esqueci!\n"
    .string "Por que me chamou?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Certo, vovô!\n"
    .string "Deixa comigo!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, odeio\n"
    .string "dizer, mas você não\l"
    .string "vai ser necessário\l"
    .string "nisso.\p"
    .string "Já sei! Vou pegar um\n"
    .string "MAPA da minha irmã!\p"
    .string "Vou dizer para ela\n"
    .string "não te emprestar um,\l"
    .string "{PLAYER}! Hahaha!\p"
    .string "Não apareça na minha\n"
    .string "casa depois disso!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "CARVALHO: {RIVAL}?\n"
    .string "Deixa eu pensar…\p"
    .string "Ah, é verdade, eu\n"
    .string "pedi para você vir!\l"
    .string "Só espere!\p"
    .string "Aqui, {PLAYER}.\p"
    .string "Há três POKéMON\n"
    .string "aqui.\p"
    .string "Haha!\p"
    .string "Os POKéMON estão\n"
    .string "dentro destas\l"
    .string "POKé BALLS.\p"
    .string "Quando eu era jovem,\n"
    .string "fui um TREINADOR\l"
    .string "POKéMON de respeito.\p"
    .string "Mas agora, na minha\n"
    .string "velhice, só tenho\l"
    .string "esses três.\p"
    .string "Você pode ficar com\n"
    .string "um. Vá, escolha!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "CARVALHO: Tenha\n"
    .string "paciência, {RIVAL}.\l"
    .string "Você também pode\l"
    .string "pegar um!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "CARVALHO: Agora,\n"
    .string "{PLAYER}.\p"
    .string "Dentro dessas três\n"
    .string "POKé BALLS há\l"
    .string "POKéMON.\p"
    .string "Qual você vai\n"
    .string "escolher para você?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "CARVALHO: Ei!\n"
    .string "Não vá embora ainda!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! CHARMANDER é sua\n"
    .string "escolha. Você deve\l"
    .string "cuidar dele com\l"
    .string "paciência.\p"
    .string "Então, {PLAYER},\n"
    .string "você quer o POKéMON\l"
    .string "de FOGO CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! SQUIRTLE é sua\n"
    .string "escolha. Vale a pena\l"
    .string "cuidar dele.\p"
    .string "Então, {PLAYER},\n"
    .string "você decidiu pelo\l"
    .string "POKéMON de ÁGUA\l"
    .string "SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Entendo! BULBASAUR é\n"
    .string "sua escolha. É muito\l"
    .string "fácil de cuidar.\p"
    .string "Então, {PLAYER},\n"
    .string "você quer o POKéMON\l"
    .string "de GRAMA BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "Este POKéMON é bem\n"
    .string "animado!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} recebeu o\n"
    .string "{STR_VAR_1} do PROF.\l"
    .string "CARVALHO!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "CARVALHO: Se um\n"
    .string "POKéMON selvagem\l"
    .string "aparecer, seu POKéMON\l"
    .string "pode batalhar.\p"
    .string "Com ele ao seu lado,\n"
    .string "você deve chegar à\l"
    .string "próxima cidade.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "CARVALHO: {PLAYER},\n"
    .string "cuide do seu jovem\l"
    .string "POKéMON fazendo ele\l"
    .string "batalhar.\p"
    .string "Ele precisa batalhar\n"
    .string "para crescer.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "CARVALHO: Oh,\n"
    .string "{PLAYER}!\l"
    .string "Como está meu velho\l"
    .string "POKéMON?\p"
    .string "Bem, parece estar se\n"
    .string "apegando mais a você.\p"
    .string "Você deve ter talento\n"
    .string "como TREINADOR\l"
    .string "POKéMON.\p"
    .string "O que é isso?\n"
    .string "Tem algo para mim?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} entregou a\n"
    .string "ENCOMENDA!$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah!\n"
    .string "É a POKé BALL\l"
    .string "especial!\p"
    .string "Eu tinha pedido.\n"
    .string "Obrigado!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "CARVALHO: Ah, é!\n"
    .string "Tenho um pedido para\l"
    .string "vocês dois.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "Na mesa está minha\n"
    .string "invenção, o POKéDEX!\p"
    .string "Ele registra dados\n"
    .string "sobre POKéMON que\l"
    .string "você viu ou pegou.\p"
    .string "É uma enciclopédia\n"
    .string "de alta tecnologia!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "CARVALHO: {PLAYER} e\n"
    .string "{RIVAL}.\l"
    .string "Levem esses com\l"
    .string "vocês.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} recebeu o\n"
    .string "POKéDEX do PROF.\l"
    .string "CARVALHO.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "CARVALHO: Você não\n"
    .string "tem dados completos\l"
    .string "só vendo POKéMON.\p"
    .string "Você precisa pegá-\n"
    .string "los para ter dados\l"
    .string "completos.\p"
    .string "Então, aqui estão\n"
    .string "ferramentas para\l"
    .string "pegar POKéMON\l"
    .string "selvagens.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} recebeu\n"
    .string "cinco POKé BALLS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Quando um POKéMON\n"
    .string "selvagem aparece, é\l"
    .string "hora de agir.\p"
    .string "Jogue uma POKé BALL\n"
    .string "nele e tente pegá-lo!\p"
    .string "Mas isso nem sempre\n"
    .string "funciona.\p"
    .string "Um POKéMON saudável\n"
    .string "pode escapar.\l"
    .string "Você tem que ter\l"
    .string "sorte!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Fazer um guia\n"
    .string "completo de todos os\l"
    .string "POKéMON do mundo…\p"
    .string "Esse era meu sonho!\p"
    .string "Mas estou velho\n"
    .string "demais. Não posso\l"
    .string "fazer isso.\p"
    .string "Então, quero que\n"
    .string "vocês dois realizem\l"
    .string "meu sonho por mim.\p"
    .string "Vão em frente, vocês\n"
    .string "dois.\p"
    .string "É uma grande missão\n"
    .string "na história POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON do mundo\n"
    .string "todo esperam por\l"
    .string "você, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "Como está seu\l"
    .string "POKéDEX?\p"
    .string "{RIVAL} já pegou\n"
    .string "alguns POKéMON e\l"
    .string "adicionou dados.\p"
    .string "Então, {PLAYER},\n"
    .string "vamos ver seu\l"
    .string "POKéDEX.\p"
    .string "…O que houve?\n"
    .string "Você não adicionou\l"
    .string "nada de novo.\p"
    .string "Vou te dar isso,\n"
    .string "então tente se\l"
    .string "esforçar mais.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "CARVALHO: Venha me\n"
    .string "ver às vezes.\p"
    .string "Afinal, quero saber\n"
    .string "como está seu\l"
    .string "POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "É como uma\n"
    .string "enciclopédia, mas as\l"
    .string "páginas estão vazias.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Aquelas são POKé\n"
    .string "BALLS. Elas contêm\l"
    .string "POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "É o último POKéMON\n"
    .string "do PROF. CARVALHO.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Aperte START para\n"
    .string "abrir o MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "A opção SALVAR está\n"
    .string "no MENU. Use sempre.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Todos os tipos\n"
    .string "POKéMON têm pontos\l"
    .string "fortes e fracos.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Há uma mensagem de\n"
    .string "e-mail aqui.\p"
    .string "…\p"
    .string "Finalmente!\n"
    .string "Os grandes TREINADORES\l"
    .string "da LIGA POKéMON\l"
    .string "estão prontos!\p"
    .string "Traga seus melhores\n"
    .string "POKéMON e veja como\l"
    .string "você é como\l"
    .string "TREINADOR!\p"
    .string "SEDE DA LIGA POKéMON\n"
    .string "PLANALTO ÍNDIGO\p"
    .string "PROF. CARVALHO, nos\n"
    .string "visite!\l"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Eu estudo POKéMON\n"
    .string "como ASSISTENTE do\l"
    .string "PROF. CARVALHO.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Oi, {PLAYER}. Aposto\n"
    .string "que você ficou amigo\l"
    .string "do seu POKéMON.\p"
    .string "A propósito, você\n"
    .string "sabia sobre a DAISY?\p"
    .string "Se você mostrar seu\n"
    .string "POKéMON para ela,\l"
    .string "pode saber o quanto\l"
    .string "ele gosta de você.\p"
    .string "Às vezes, ela até\n"
    .string "cuida de um POKéMON\l"
    .string "para você.\p"
    .string "É segredo, então não\n"
    .string "conte para ninguém.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "O PROF. CARVALHO vai\n"
    .string "ter seu próprio\l"
    .string "programa de rádio.\p"
    .string "O programa se\n"
    .string "chamará SEMINÁRIO\l"
    .string "POKéMON do PROF.\l"
    .string "CARVALHO.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "O PROF. CARVALHO não\n"
    .string "parece muito, mas é\l"
    .string "autoridade em\l"
    .string "POKéMON.\p"
    .string "Muitos TREINADORES\n"
    .string "POKéMON o respeitam\l"
    .string "muito.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, isso é excelente!\p"
    .string "{PLAYER}, tenho\n"
    .string "outro pedido\l"
    .string "importante.\p"
    .string "Preciso que você\n"
    .string "preste atenção.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recentemente, têm\n"
    .string "visto muitas espécies\l"
    .string "raras de POKéMON.\p"
    .string "Falo de POKéMON que\n"
    .string "nunca foram vistos em\l"
    .string "KANTO.\p"
    .string "Adoraria ver por mim\n"
    .string "mesmo, mas sou velho\l"
    .string "demais.\p"
    .string "Como não posso,\n"
    .string "{PLAYER}, gostaria\l"
    .string "que você fosse.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Ei, ouvi\n"
    .string "isso!\p"
    .string "Vovô, por que você\n"
    .string "sempre prefere o\l"
    .string "{PLAYER}?\p"
    .string "Eu peguei mais\n"
    .string "POKéMON, e mais\l"
    .string "rápido também.\p"
    .string "Você devia deixar\n"
    .string "tudo comigo.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "CARVALHO: Eu sei, eu\n"
    .string "sei. Claro que preciso\l"
    .string "da sua ajuda também.\p"
    .string "Agora, preciso ver os\n"
    .string "POKéDEX de vocês.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "O PROF. CARVALHO\n"
    .string "pegou os dois POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…E está pronto!\p"
    .string "Agora eles podem\n"
    .string "gravar dados de\l"
    .string "muitos mais POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "O POKéDEX de\n"
    .string "{PLAYER} foi\l"
    .string "melhorado!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Agora, {PLAYER} e\n"
    .string "{RIVAL}!\p"
    .string "Desta vez, vocês\n"
    .string "devem trabalhar para\l"
    .string "encher os POKéDEX.\p"
    .string "Peço que façam os\n"
    .string "melhores e mais\l"
    .string "completos de todos os\l"
    .string "tempos!\p"
    .string "Realmente, é uma\n"
    .string "grande missão na\l"
    .string "história POKéMON!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Vovô, se\n"
    .string "acalme. Não fique tão\l"
    .string "empolgado.\p"
    .string "Vou completar o\n"
    .string "POKéDEX, não se\l"
    .string "preocupe.\p"
    .string "Acho que vou olhar na\n"
    .string "ILHA UM primeiro…\p"
    .string "Enfim, estou indo!$"

