PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MÃE: …Certo.\n"
    .string "Todo menino sai de\n"
    .string "casa um dia.\l"
    .string "Foi o que falaram\n"
    .string "na TV.\p"
    .string "Ah, sim. O PROF.\n"
    .string "CARVALHO, da casa ao\n"
    .string "lado, te procurava.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MÃE: …Certo.\n"
    .string "Toda menina sonha\n"
    .string "em viajar.\l"
    .string "Foi o que falaram\n"
    .string "na TV.\p"
    .string "Ah, sim. O PROF.\n"
    .string "CARVALHO, da casa ao\n"
    .string "lado, te procurava.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MÃE: {PLAYER}!\n"
    .string "Você devia descansar\n"
    .string "um pouco.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MÃE: Que bom! Você e\n"
    .string "seus POKéMON estão\n"
    .string "ótimos.\l"
    .string "Cuide-se bem!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Tem um filme na TV.\n"
    .string "Quatro meninos andam\n"
    .string "nos trilhos do trem.\l"
    .string "…Eu devia ir também.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Tem um filme na TV.\n"
    .string "Uma menina de\n"
    .string "tranças anda por uma\n"
    .string "estrada de tijolos.\l"
    .string "…Eu devia ir também.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Ops, lado errado…$"

