PalletTown_Text_OakDontGoOut::
    .string "CARVALHO: Ei!\n"
    .string "Espera!\l"
    .string "Não saia!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "CARVALHO: É\n"
    .string "perigoso!\l"
    .string "POKéMON selvagens\l"
    .string "vivem na grama alta!\p"
    .string "Você precisa do seu\n"
    .string "próprio POKéMON para\l"
    .string "se proteger.\p"
    .string "Já sei!\n"
    .string "Venha comigo!$"

PalletTown_Text_RaisingMonsToo::
    .string "Também estou criando\n"
    .string "POKéMON.\p"
    .string "Quando ficam fortes,\n"
    .string "podem me proteger.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "A tecnologia é\n"
    .string "incrível!\p"
    .string "Agora você pode\n"
    .string "guardar itens e\l"
    .string "POKéMON como dados\l"
    .string "no PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "LAB DE PESQUISAS\n"
    .string "POKéMON CARVALHO$"

PalletTown_Text_PlayersHouse::
    .string "Casa de {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "Casa de {RIVAL}$"

PalletTown_Text_TownSign::
    .string "VILA PALETTE\n"
    .string "Tons da sua jornada\l"
    .string "esperam por você!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "CARVALHO: Ah,\n"
    .string "{PLAYER}!\l"
    .string "Você voltou?\p"
    .string "Quanto você já\n"
    .string "preencheu do seu\l"
    .string "POKéDEX?\p"
    .string "Posso ver?\p"
    .string "Vejamos…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Você pegou\n"
    .string "{STR_VAR_2}…\p"
    .string "Hm, parece que você\n"
    .string "está se esforçando\l"
    .string "de verdade.\p"
    .string "Quando preencher mais\n"
    .string "um pouco, venha me\l"
    .string "mostrar.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Você pegou…\n"
    .string "{STR_VAR_2}!?\l"
    .string "Isso é impressionante!\p"
    .string "Tem algo que queria\n"
    .string "pedir, {PLAYER}.\p"
    .string "Venha.\n"
    .string "Me siga.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "CARVALHO: Ah,\n"
    .string "{PLAYER}!\l"
    .string "Parece estar gostando\l"
    .string "de viajar.\p"
    .string "Conhecendo você,\n"
    .string "{PLAYER}, posso\l"
    .string "imaginar indo a\l"
    .string "lugares exóticos.\p"
    .string "Bom para você.\n"
    .string "Hohoho.$"

